[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "AmbientLife"
versionNumber = "1.0.0"
description = "Adds ambient wildlife and creatures for atmosphere. Includes butterflies, birds, fireflies, and more passive creatures."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-AmbientLife"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/AmbientLife.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
