[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "MorePlanters_Updated"
versionNumber = "3.0.5"
description = "Adds Planter MKII (configurable speed, double yield) and MKIII (integrated Thresher). Updated for EMU 6.1.3."
websiteUrl = "https://github.com/CubeSuite/TTMod-MorePlanters"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net472/MorePlanters.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
