[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "CertiFriedModpack"
versionNumber = "1.0.4"
description = "Complete CertiFried mod collection for Techtonica. Adds advanced machines, new gameplay systems, logistics, exploration creatures, and quality-of-life improvements."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-EMU613-Mods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.2.0"
CertiFried-AdvancedMachines = "2.4.2"
CertiFried-AtlantumReactor_Updated = "4.0.11"
CertiFried-BeltImmunity_Updated = "1.0.4"
CertiFried-ChainExplosives_Updated = "1.0.4"
CertiFried-DevTools = "2.2.0"
CertiFried-EnhancedLogistics = "3.2.2"
CertiFried-HazardousWorld = "1.5.0"
CertiFried-MobilityPlus = "1.7.0"
CertiFried-MorePlanters_Updated = "3.0.9"
CertiFried-NarrativeExpansion = "2.1.0"
CertiFried-OmniseekerPlus = "1.0.7"
CertiFried-PlanterCoreClusters_Updated = "3.0.7"
CertiFried-Restock_Updated = "3.0.8"
CertiFried-SurvivalElements = "2.6.1"
CertiFried-WormholeChests_Updated = "3.1.1"
CertiFried-AmbientLife = "2.0.1"
CertiFried-AtlantumEnrichment = "1.0.1"
CertiFried-BioProcessing = "1.0.1"
CertiFried-DroneLogistics = "1.1.1"
CertiFried-PetsCompanions = "1.4.2"
CertiFried-Recycler = "1.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
