[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "EnhancedLogistics"
versionNumber = "2.0.5"
description = "Enhanced logistics system for Techtonica with Search UI, Storage Network, and Drone Delivery. Search inventories globally, link chests together, automate item transfers."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-EMU613-Mods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/EnhancedLogistics.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
