[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "TurretDefense"
versionNumber = "4.3.0"
description = "EPIC BOSS BATTLES! Adds defensive turrets, alien waves, and 5 unique boss encounters (Overlord, Behemoth, Hivemind, Dreadnought, Harvester). Custom Defense tab in tech tree!"
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-TurretDefense"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/TurretDefense.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
