[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "AdvancedMachines"
versionNumber = "2.0.3"
description = "Adds Tier 4 and Tier 5 versions of Smelters, Assemblers, Drills, Threshers, and Planters with increased speeds. Also enables Hidden Machine Variants."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-EMU613-Mods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./build/icon.png"
readme = "./README.md"
changelog = "./CHANGELOG.md"
outdir = "./build"

[[build.copy]]
source = "./build/AdvancedMachines.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
