[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "Restock_Updated"
versionNumber = "3.0.5"
description = "Automatically restocks items from your inventory when placing machines or items. Updated for EMU 6.1.3. Original mod by Equinox."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-EMU613-Mods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./thunderstore/icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./thunderstore/Restock.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
