[config]
schemaVersion = "0.0.1"

[package]
namespace = "CertiFried"
name = "ChainExplosives_Updated"
versionNumber = "1.0.1"
description = "Interact with one explosive to detonate ALL placed explosives at once! Chain reaction mining!"
websiteUrl = "https://github.com/CubeSuite/TTMod-ChainExplosives"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./thunderstore_build"

[[build.copy]]
source = "./bin/Release/net472/ChainExplosives.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
