[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "DevTools"
versionNumber = "2.1.1"
description = "In-game developer tools with GUI for Techtonica. Toggle game modes, player stats, machine speeds, protection zones, safe sprint, and more. Now includes CasperProtections features! Press F8 to open."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-EMU613-Mods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./build/icon.png"
readme = "./README.md"
changelog = "./CHANGELOG.md"
outdir = "./build"

[[build.copy]]
source = "./build/DevTools.dll"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
