[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "CoreComposerPlus"
versionNumber = "1.0.0"
description = "Enhances the Memory Tree (Core Composer) with batch processing and speed options. Process multiple cores at once or enable instant mode."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-TechtonicaMods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/CoreComposerPlus.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
