[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "SeamlessWorld"
versionNumber = "0.1.0"
description = "Removes floor barriers to create a continuous world. All floors load simultaneously, allowing vertical traversal without loading screens. Fall down elevator shafts or build factories spanning multiple levels!"
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-TechtonicaMods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
CertiFried-TechtonicaFramework = "1.4.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/SeamlessWorld.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
