[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "AtlantumReactor_Updated"
versionNumber = "4.0.9"
description = "Adds the Atlantum Reactor - a 20MW endgame power generator that consumes Atlantum Mixture Bricks and Shiverthorn Coolant. Features a distinctive green radioactive tint."
websiteUrl = "https://github.com/xXDeath420Xx/AtlantumReactor"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/AtlantumReactor.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
