[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "AtlantumReactor_Updated"
versionNumber = "4.0.2"
description = "Updated Atlantum Reactor - a 20MW endgame power generator. Originally created by Equinox, maintained by CertiFried. Consumes Atlantum Mixture Bricks and Shiverthorn Coolant."
websiteUrl = "https://github.com/xXDeath420Xx/CertiFried-EMU613-Mods"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./build/icon.png"
readme = "./README.md"
changelog = "./CHANGELOG.md"
outdir = "./build"

[[build.copy]]
source = "./build/AtlantumReactor.dll"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
