[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "AtlantumReactor_Updated"
versionNumber = "3.0.3"
description = "Adds an end-game Atlantum Reactor for high-power generation. Updated for EMU 6.1.3. Original mod by Equinox."
websiteUrl = "https://github.com/CubeSuite/AtlantumReactor"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./build/icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./build/AtlantumReactor.dll"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
